18F/data-act-pilot

.gitignore, schema/data-act-schema.proto
Changed the schema to nest objects instead of referencing them by ID.
This uses "Action" as the most granular object. A new image will be
forthcoming.
=> Tweak and add schema from 18f/data-act-schemas

JAAMSPrism.ipynb, mappings/sba.py
This includes the mapping file for matching protobuf schema attributes to SBA record fields or functions. Still working on it, but it can be merged to facilitate other work if need be.
=> SBA mapping

sba-business-rules.md
This is the first draft of SBA business rules and validations and will be updated.
=> WIP business rules

README.md, processors/get_sam_data.py
Adds a section to the README describing the SAM API lookup utility,
with examples. Also prettifies the output of the utility.
=> Updates README with SAM API utility usage

sba-business-rules.md
Noticed that including data relationships was a task in the business rules user story.
=> add info about join validations

processors/validator.py
Currently does basic field level validation.
Usage: python validator.py -i infile
Infile should be the output of process_sba.py
=> Add basic validation script

processors/validator.py, sba-business-rules.md
Updated the following: 
validator.py 
- business name
- business address
- business type
sba-business-rules.md
- Documented the validation step and what each step would include
- Authoritative sources
- Added research question at the bottom about authoritative sources
=> Add validators & updated business rules

process.md
this is an acceptance criteria for #51
=> add field list for agency csvs

processors/validator.py
Previous version would choke on field names nested in the repeated fields.
This adds a fix for that, pulling results from each instance of a repeated
field. Also updates the checks to support the results of the updated
get_values() function, and adds better summary results.
=> Adds support for repeated fields

README.md
What do you think about this wording as way to signal that this is not official DATA Act guidance? @micahsaul @elainekamlley if you think this looks ok, I'll send it along for review.
=> add some clarification about the purpose of the project

INSTALL.md, README.md, bootstrap.sh, sba-business-rules.md
=> updates to reflect repo name change

sba-business-rules.md
@bsweger - took a stab at it. Take a look and please let me know additional edits.
=> WIP adding contract specific business rules

data-act-agency-demo.ipynb
Update the notebook demo template to add links to repo and a demo of the validation processor.
=> update demo notebook for workshop screencast

README.md
Ori weighed in on this and gave a thumbs up.
=> more clarity about project & its role

processors/compare_sam_addresses.py, processors/get_sam_data.py
Compares docvendor address with addresses from the SAM API. If street number,
street name, city, and state match between the two systems, it is considered
a pass.
=> Compare addresses from SBA with SAM

template/playbook-digest.md
Here is the first go at the digest. I added specifics about the SBA pilot since I thought it might be helpful to see how we have handled some of the playbook steps. Please review, and provide me with any feedback.
=> first draft of playbook digest

processors/validator.py
And passes over line breaks in the data
=> Raises award ID instead of record number in validator

app/app.py, bootstrap.sh, requirements.txt
This adds a basic flask web app to the project.
I was having trouble installing certain dependencies, like pandas,
this will have to be resolved.
=> Add flask web app

app/app.py, app/templates/home.html
The user needs to upload a file so it can be processed and
validated. This starts that work by allowing for a simple file upload
which then echos the user the name of the file they uploaded.
=> Basic csv file upload

app/requirements.txt, app/src/css/main.css, app/templates/layout.html, manifest.yml, requirements.txt
ignore the misnomer of the branch.
=> Basic HTML and CSS structure 

app/DEPLOY.md
Wrote up some quick deployment instructions. There are more direct commands so let me know if I should add those. As a practice however, I always like to add the long form so folks know exactly what is happening at each step.  Please let me know if you have any feedback. @msecret @bsweger
=> added deploy instruction for application

.gitignore, package.json
Improves the build by adding file watching and ensuring all
directories are made and all files are copied.
=> Improve build

.gitignore, app/app.py, app/templates/home.html, package.json
Tracking off https://github.com/18F/data-act-pilot/pull/124
Code to check if each file exists, is a valid csv and has valid
headers.
Note: I haven't implemented the actual correct headers yet, I will
use constants though.
=> File check

app/app.py, app/templates/home.html
This adds all the correct csv file headers as contants so the upload
process checks against more then dummy data. It also keeps a correct
file list so the user can see what files were successful on the front
end.
=> Correct csv file headers and correct files

validator/validator.py
Fixes an issue where the validator was running all checks against
nonrequired, blank fields.
=> Logic fixes for nonrequired fields

processors/process_source.py
Fixes for the code that generates the dummy data
=> fix column names; get rid of .0 in int fields

app/src/css/reset.css, app/src/css/screen.css, app/templates/home.html
Puts the styling of the errors into a table to make them easier to read.
=> Improve styling of errors with table

app/app.py, app/src/css/screen.css, app/static/css/screen.css, app/templates/home.html, app/validator/validator.py
We're attempting to provide an identifier so the user can fix the
data back in their system at the source. Becky suggested these
combination of fields to get the TAS.
Currently, the logic is if the field doesn't exist in the data, just
not include it. This might not be the best logic because it
make make the number more confusing. Another option is to include
the number 0 where the data doesn't exist. This depends on what
the user would expect.
=> Row identifier

.gitignore
In which a data geek makes a movie
=> add screencast

README.md
Kristina tested this .avi version of the screencast, and it works on her older version of Windows Media Player.
=> add screencast that will play on older versions of Windows Media PLayer

README.md, docs/BACKGROUND.md, docs/DEPLOY.md, docs/HOWTO.md, docs/INSTALL.md
Exploring the reorganized branch, and I like this very much. Makes sense, well structured. Made some content styling edits per 18F style and made a few language tweaks.
=> Content edits

app/src/css/screen.css, app/static/css/screen.css, app/templates/home.html, app/templates/layout.html
@msecret -- this is ready for review. They are minor changes but maybe adds a little more clarity to the user. This will close #174 
Also, this copy will likely change once the conversion feature is in place.
=> added web app copy

processors/xbrl/xbrl_translate.py
Was getting some errors when reading the .csvs, so added a flag to open them in universal newline mode.
=> open csvs in universal newline mode

bootstrap.sh
This eliminates some of the problems with other dependencies.
=> Changed bootstrap to use app requirements file

docs/BACKGROUND.md
Adding mac and newer windows compatible screencast that includes footage of updated web app. 
TODO: compatible format for older version of windows
=> movie and links

docs/BACKGROUND.md
Trying to add all the screencasts!
=> adding avi screencast

app/validator/validator.py
This was causing this morning's deploy issue. Remove a line of code from a feature that I had started and then abandoned...committed part of it by accident.
=> remove stray line of code

.gitignore, app/app.py, app/templates/home.html
Adds Download CSV link and CSV Display option to the validation results.
=> Csv output

app/app.py
This removes the hard-coded dictionary of valid header names for the uploaded .csv files. The new code replaces the hard-coded dictionary by reading each .csv file in validator/rules/ and grabbing its _fieldname_ values.
=> generate valid headers list dynamically

app/app.py
Adds row number to CSV output and enumerates missing columns.
=> Add row number and missing columns

app/app.py, app/templates/home.html, app/validator/validator.py
In both web and csv presentation of errors, the submitted value will now
show up. Also, cleared up relative directory issue which effected
validation when the app was started from repo root.
=> Add submitted value to error output

app/app.py, app/templates/home.html, app/validator/validator.py
This PR fixes three bugs:
* #220: remove the link that doesn't go anywhere
* #229: fix bug that was causing an error when user uploads a file with no errors
* #231: fix dict lookup that threw an error if a designated key field isn't in an uploaded file
* if an incoming field contains nothing but whitespace characters, treat it as a missing data
=> Misc fixes
